import React, { useState } from "react";
import { base44 } from "@/api/base44Client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { BarChart2, Download, Mail, Calendar, TrendingUp, DollarSign, Users, Loader2 } from "lucide-react";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, LineChart, Line } from "recharts";

export default function ReportsManager({ affiliates, referrals, payouts }) {
  const [period, setPeriod] = useState("30");
  const [sending, setSending] = useState(false);
  const [sent, setSent] = useState(false);

  const cutoff = new Date(Date.now() - parseInt(period) * 24 * 60 * 60 * 1000);
  const periodRefs = referrals.filter(r => new Date(r.created_date) >= cutoff);
  const periodPayouts = payouts.filter(p => new Date(p.created_date) >= cutoff);

  // Build daily data for the period
  const dailyData = [];
  for (let i = parseInt(period) - 1; i >= 0; i--) {
    const day = new Date(Date.now() - i * 24 * 60 * 60 * 1000);
    const dateStr = day.toLocaleDateString("en-US", { month: "short", day: "numeric" });
    const dayRefs = referrals.filter(r => new Date(r.created_date).toDateString() === day.toDateString());
    const dayPay = payouts.filter(p => new Date(p.created_date).toDateString() === day.toDateString());
    dailyData.push({
      date: dateStr,
      referrals: dayRefs.length,
      conversions: dayRefs.filter(r => r.status === "converted").length,
      payouts: dayPay.reduce((s, p) => s + (p.amount || 0), 0),
    });
  }

  // Cohort analysis: group affiliates by join month
  const cohorts = {};
  affiliates.forEach(a => {
    const month = new Date(a.created_date).toLocaleDateString("en-US", { year: "numeric", month: "short" });
    if (!cohorts[month]) cohorts[month] = { month, count: 0, conversions: 0, earned: 0 };
    cohorts[month].count++;
    cohorts[month].conversions += a.totalConversions || 0;
    cohorts[month].earned += a.totalEarned || 0;
  });
  const cohortData = Object.values(cohorts).slice(-6);

  // Top performers
  const topAffiliates = [...affiliates]
    .sort((a, b) => (b.totalEarned || 0) - (a.totalEarned || 0))
    .slice(0, 5);

  const sendReport = async () => {
    setSending(true);
    const adminEmail = "mail@ezpayamerica.com";
    const convRate = periodRefs.length > 0 ? ((periodRefs.filter(r => r.status === "converted").length / periodRefs.length) * 100).toFixed(1) : 0;
    await base44.integrations.Core.SendEmail({
      to: adminEmail,
      subject: `Affiliate Program Report — Last ${period} Days`,
      body: `
AFFILIATE PROGRAM REPORT
Period: Last ${period} days

SUMMARY
• Total Referrals: ${periodRefs.length}
• Conversions: ${periodRefs.filter(r => r.status === "converted").length} (${convRate}%)
• Total Payouts: $${periodPayouts.reduce((s, p) => s + (p.amount || 0), 0).toFixed(2)}
• Active Affiliates: ${affiliates.filter(a => a.status === "approved").length}

TOP PERFORMERS
${topAffiliates.map((a, i) => `${i + 1}. ${a.firstName} ${a.lastName} — $${(a.totalEarned || 0).toFixed(2)} earned, ${a.totalConversions || 0} conversions`).join("\n")}

Generated by EzPay America Affiliate Admin
      `.trim()
    });
    setSending(false);
    setSent(true);
    setTimeout(() => setSent(false), 3000);
  };

  const exportCSV = () => {
    const rows = [
      ["Date", "Referrals", "Conversions", "Payouts ($)"],
      ...dailyData.map(d => [d.date, d.referrals, d.conversions, d.payouts.toFixed(2)])
    ];
    const csv = rows.map(r => r.join(",")).join("\n");
    const blob = new Blob([csv], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `affiliate-report-${period}d.csv`;
    a.click();
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap gap-3 items-center justify-between">
        <div className="flex items-center gap-2">
          <Select value={period} onValueChange={setPeriod}>
            <SelectTrigger className="w-36"><SelectValue /></SelectTrigger>
            <SelectContent>
              <SelectItem value="7">Last 7 days</SelectItem>
              <SelectItem value="30">Last 30 days</SelectItem>
              <SelectItem value="90">Last 90 days</SelectItem>
              <SelectItem value="365">Last 12 months</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={exportCSV}><Download className="w-4 h-4 mr-1" />Export CSV</Button>
          <Button variant="outline" onClick={sendReport} disabled={sending} className="border-blue-300 text-blue-700">
            {sending ? <Loader2 className="w-4 h-4 animate-spin mr-1" /> : <Mail className="w-4 h-4 mr-1" />}
            {sent ? "Sent!" : "Email Report"}
          </Button>
        </div>
      </div>

      {/* KPIs */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        {[
          { label: "Referrals", value: periodRefs.length, icon: Users, color: "text-blue-600" },
          { label: "Conversions", value: periodRefs.filter(r => r.status === "converted").length, icon: TrendingUp, color: "text-green-600" },
          { label: "Conversion Rate", value: `${periodRefs.length > 0 ? ((periodRefs.filter(r => r.status === "converted").length / periodRefs.length) * 100).toFixed(1) : 0}%`, icon: BarChart2, color: "text-amber-600" },
          { label: "Total Payouts", value: `$${periodPayouts.reduce((s, p) => s + (p.amount || 0), 0).toFixed(0)}`, icon: DollarSign, color: "text-emerald-600" },
        ].map((s, i) => (
          <Card key={i} className="border-none shadow">
            <CardContent className="p-4">
              <p className="text-xs text-gray-500">{s.label}</p>
              <p className={`text-2xl font-bold ${s.color}`}>{s.value}</p>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Daily Referrals Chart */}
      <Card className="border-none shadow-lg">
        <CardHeader><CardTitle className="flex items-center gap-2"><Calendar className="w-5 h-5" />Daily Activity</CardTitle></CardHeader>
        <CardContent>
          <ResponsiveContainer width="100%" height={240}>
            <BarChart data={dailyData.slice(-30)}>
              <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
              <XAxis dataKey="date" tick={{ fontSize: 11 }} interval={Math.floor(dailyData.length / 8)} />
              <YAxis tick={{ fontSize: 11 }} />
              <Tooltip />
              <Bar dataKey="referrals" fill="#93c5fd" name="Referrals" radius={[2, 2, 0, 0]} />
              <Bar dataKey="conversions" fill="#6ee7b7" name="Conversions" radius={[2, 2, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </CardContent>
      </Card>

      {/* Cohort Analysis */}
      <Card className="border-none shadow-lg">
        <CardHeader><CardTitle className="flex items-center gap-2"><TrendingUp className="w-5 h-5" />Cohort Analysis (by Join Month)</CardTitle></CardHeader>
        <CardContent>
          {cohortData.length === 0 ? (
            <p className="text-gray-400 text-center py-8">No data yet</p>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b text-left text-gray-500">
                    <th className="pb-3 font-medium">Cohort (Join Month)</th>
                    <th className="pb-3 font-medium">Affiliates</th>
                    <th className="pb-3 font-medium">Conversions</th>
                    <th className="pb-3 font-medium">Avg Conv/Affiliate</th>
                    <th className="pb-3 font-medium">Total Earned</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  {cohortData.map(c => (
                    <tr key={c.month} className="hover:bg-gray-50">
                      <td className="py-3 font-medium text-gray-900">{c.month}</td>
                      <td className="py-3 text-blue-600 font-semibold">{c.count}</td>
                      <td className="py-3 text-green-600 font-semibold">{c.conversions}</td>
                      <td className="py-3 text-gray-600">{c.count > 0 ? (c.conversions / c.count).toFixed(1) : 0}</td>
                      <td className="py-3 text-emerald-600 font-semibold">${c.earned.toFixed(0)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Top Performers */}
      <Card className="border-none shadow-lg">
        <CardHeader><CardTitle>Top 5 Performers (All Time)</CardTitle></CardHeader>
        <CardContent>
          <div className="space-y-3">
            {topAffiliates.map((a, i) => (
              <div key={a.id} className="flex items-center gap-3 p-3 bg-gray-50 rounded-xl">
                <div className="w-7 h-7 rounded-full bg-amber-500 flex items-center justify-center text-white font-bold text-sm flex-shrink-0">
                  {i + 1}
                </div>
                <div className="flex-1">
                  <p className="font-semibold text-gray-900">{a.firstName} {a.lastName}</p>
                  <p className="text-xs text-gray-500">{a.totalConversions || 0} conversions · {a.totalReferrals || 0} referrals</p>
                </div>
                <div className="text-right">
                  <p className="font-bold text-green-600">${(a.totalEarned || 0).toFixed(0)}</p>
                  <p className="text-xs text-gray-400">earned</p>
                </div>
              </div>
            ))}
            {topAffiliates.length === 0 && <p className="text-gray-400 text-center py-6">No affiliate data yet.</p>}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}